### ISSUE TITLE
Diseño y alcance del Proyecto

### ISSUE THREAD

**Issue by cristiandley** [gdgnqnnt/EventsUnc#1]
Este tema lo vamos a hablar en una reunión o lo podemos ir avanzando por acá ? (_de ser tema para clase, no duden en cerrar mi issue_)

Estaría bueno ir viendo que se puede hacer en este repo, o en que se puede ayudar. Para eso deberíamos contar con al menos un esquema mínimo. 

- [ ] Requerimientos
- [ ] Modelo de Datos
- [ ] Casos de Usos
- [ ] Estructura de componentes
- [ ] Alcance de los componentes
- [ ] Stack Cliente
- [ ] Stack Server
- [ ] Utilizar la solapa [Projects](https://github.com/gdgnqnnt/EventsUnc/projects) o  alguna herramienta 
como [Asana](http://asana.com/) ... Trello... o cualquier herramienta que tenga formato Kanban.

**Comment by cristiandley** [comment]
### Requerimientos
Respondo el issue agregando los requerimientos (luego deberiamos utilizar la wiki)

La Universidad de Economía requiere un calendario para administrar los eventos por aula.


Si bien aca definimos entidades, en Mongo(NoSql) la estructura no deberia realizar Joins. Por lo tanto deberiamos desarrollar un modelo apto para tal.

```bash
- Evento
  -  Espacio
  -  Fecha/Hora inicio
  -  Fehca/Hora Fin
  -  Zonas
  -  Descripción
  -  Profesor
  -  Estado

- Espacio
  - Espacio
  - Descripción

- Notificación
  - Descripción
```

@sebahc  @elpagano  verifiquen por favor.

**Comment by elpagano** [comment]
El Stack del server lo vamos a definir en base a lo que hablemos con el área técnica de la facultad y su disponibilidad de internet en la facu y de servidores internos.
